"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _Type:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _TypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Type.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    initial_feed: _Type.ValueType  # 0
    live_feed: _Type.ValueType  # 1
    market_info: _Type.ValueType  # 2

class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...

initial_feed: Type.ValueType  # 0
live_feed: Type.ValueType  # 1
market_info: Type.ValueType  # 2
Global___Type: _TypeAlias = Type  # noqa: Y015

class _RequestMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RequestModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_RequestMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ltpc: _RequestMode.ValueType  # 0
    full_d5: _RequestMode.ValueType  # 1
    option_greeks: _RequestMode.ValueType  # 2
    full_d30: _RequestMode.ValueType  # 3

class RequestMode(_RequestMode, metaclass=_RequestModeEnumTypeWrapper): ...

ltpc: RequestMode.ValueType  # 0
full_d5: RequestMode.ValueType  # 1
option_greeks: RequestMode.ValueType  # 2
full_d30: RequestMode.ValueType  # 3
Global___RequestMode: _TypeAlias = RequestMode  # noqa: Y015

class _MarketStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _MarketStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_MarketStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PRE_OPEN_START: _MarketStatus.ValueType  # 0
    PRE_OPEN_END: _MarketStatus.ValueType  # 1
    NORMAL_OPEN: _MarketStatus.ValueType  # 2
    NORMAL_CLOSE: _MarketStatus.ValueType  # 3
    CLOSING_START: _MarketStatus.ValueType  # 4
    CLOSING_END: _MarketStatus.ValueType  # 5

class MarketStatus(_MarketStatus, metaclass=_MarketStatusEnumTypeWrapper): ...

PRE_OPEN_START: MarketStatus.ValueType  # 0
PRE_OPEN_END: MarketStatus.ValueType  # 1
NORMAL_OPEN: MarketStatus.ValueType  # 2
NORMAL_CLOSE: MarketStatus.ValueType  # 3
CLOSING_START: MarketStatus.ValueType  # 4
CLOSING_END: MarketStatus.ValueType  # 5
Global___MarketStatus: _TypeAlias = MarketStatus  # noqa: Y015

@_typing.final
class LTPC(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LTP_FIELD_NUMBER: _builtins.int
    LTT_FIELD_NUMBER: _builtins.int
    LTQ_FIELD_NUMBER: _builtins.int
    CP_FIELD_NUMBER: _builtins.int
    ltp: _builtins.float
    ltt: _builtins.int
    ltq: _builtins.int
    cp: _builtins.float
    def __init__(
        self,
        *,
        ltp: _builtins.float = ...,
        ltt: _builtins.int = ...,
        ltq: _builtins.int = ...,
        cp: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cp", b"cp", "ltp", b"ltp", "ltq", b"ltq", "ltt", b"ltt"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LTPC: _TypeAlias = LTPC  # noqa: Y015

@_typing.final
class MarketLevel(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BIDASKQUOTE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def bidAskQuote(self) -> _containers.RepeatedCompositeFieldContainer[Global___Quote]: ...
    def __init__(
        self,
        *,
        bidAskQuote: _abc.Iterable[Global___Quote] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bidAskQuote", b"bidAskQuote"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MarketLevel: _TypeAlias = MarketLevel  # noqa: Y015

@_typing.final
class MarketOHLC(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OHLC_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ohlc(self) -> _containers.RepeatedCompositeFieldContainer[Global___OHLC]: ...
    def __init__(
        self,
        *,
        ohlc: _abc.Iterable[Global___OHLC] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ohlc", b"ohlc"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MarketOHLC: _TypeAlias = MarketOHLC  # noqa: Y015

@_typing.final
class Quote(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BIDQ_FIELD_NUMBER: _builtins.int
    BIDP_FIELD_NUMBER: _builtins.int
    ASKQ_FIELD_NUMBER: _builtins.int
    ASKP_FIELD_NUMBER: _builtins.int
    bidQ: _builtins.int
    bidP: _builtins.float
    askQ: _builtins.int
    askP: _builtins.float
    def __init__(
        self,
        *,
        bidQ: _builtins.int = ...,
        bidP: _builtins.float = ...,
        askQ: _builtins.int = ...,
        askP: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["askP", b"askP", "askQ", b"askQ", "bidP", b"bidP", "bidQ", b"bidQ"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Quote: _TypeAlias = Quote  # noqa: Y015

@_typing.final
class OptionGreeks(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DELTA_FIELD_NUMBER: _builtins.int
    THETA_FIELD_NUMBER: _builtins.int
    GAMMA_FIELD_NUMBER: _builtins.int
    VEGA_FIELD_NUMBER: _builtins.int
    RHO_FIELD_NUMBER: _builtins.int
    delta: _builtins.float
    theta: _builtins.float
    gamma: _builtins.float
    vega: _builtins.float
    rho: _builtins.float
    def __init__(
        self,
        *,
        delta: _builtins.float = ...,
        theta: _builtins.float = ...,
        gamma: _builtins.float = ...,
        vega: _builtins.float = ...,
        rho: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["delta", b"delta", "gamma", b"gamma", "rho", b"rho", "theta", b"theta", "vega", b"vega"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OptionGreeks: _TypeAlias = OptionGreeks  # noqa: Y015

@_typing.final
class OHLC(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INTERVAL_FIELD_NUMBER: _builtins.int
    OPEN_FIELD_NUMBER: _builtins.int
    HIGH_FIELD_NUMBER: _builtins.int
    LOW_FIELD_NUMBER: _builtins.int
    CLOSE_FIELD_NUMBER: _builtins.int
    VOL_FIELD_NUMBER: _builtins.int
    TS_FIELD_NUMBER: _builtins.int
    interval: _builtins.str
    open: _builtins.float
    high: _builtins.float
    low: _builtins.float
    close: _builtins.float
    vol: _builtins.int
    ts: _builtins.int
    def __init__(
        self,
        *,
        interval: _builtins.str = ...,
        open: _builtins.float = ...,
        high: _builtins.float = ...,
        low: _builtins.float = ...,
        close: _builtins.float = ...,
        vol: _builtins.int = ...,
        ts: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["close", b"close", "high", b"high", "interval", b"interval", "low", b"low", "open", b"open", "ts", b"ts", "vol", b"vol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OHLC: _TypeAlias = OHLC  # noqa: Y015

@_typing.final
class MarketFullFeed(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LTPC_FIELD_NUMBER: _builtins.int
    MARKETLEVEL_FIELD_NUMBER: _builtins.int
    OPTIONGREEKS_FIELD_NUMBER: _builtins.int
    MARKETOHLC_FIELD_NUMBER: _builtins.int
    ATP_FIELD_NUMBER: _builtins.int
    VTT_FIELD_NUMBER: _builtins.int
    OI_FIELD_NUMBER: _builtins.int
    IV_FIELD_NUMBER: _builtins.int
    TBQ_FIELD_NUMBER: _builtins.int
    TSQ_FIELD_NUMBER: _builtins.int
    atp: _builtins.float
    """avg traded price"""
    vtt: _builtins.int
    """volume traded today"""
    oi: _builtins.float
    """open interest"""
    iv: _builtins.float
    """implied volatility"""
    tbq: _builtins.float
    """total buy quantity"""
    tsq: _builtins.float
    """total sell quantity"""
    @_builtins.property
    def ltpc(self) -> Global___LTPC: ...
    @_builtins.property
    def marketLevel(self) -> Global___MarketLevel: ...
    @_builtins.property
    def optionGreeks(self) -> Global___OptionGreeks: ...
    @_builtins.property
    def marketOHLC(self) -> Global___MarketOHLC: ...
    def __init__(
        self,
        *,
        ltpc: Global___LTPC | None = ...,
        marketLevel: Global___MarketLevel | None = ...,
        optionGreeks: Global___OptionGreeks | None = ...,
        marketOHLC: Global___MarketOHLC | None = ...,
        atp: _builtins.float = ...,
        vtt: _builtins.int = ...,
        oi: _builtins.float = ...,
        iv: _builtins.float = ...,
        tbq: _builtins.float = ...,
        tsq: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ltpc", b"ltpc", "marketLevel", b"marketLevel", "marketOHLC", b"marketOHLC", "optionGreeks", b"optionGreeks"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["atp", b"atp", "iv", b"iv", "ltpc", b"ltpc", "marketLevel", b"marketLevel", "marketOHLC", b"marketOHLC", "oi", b"oi", "optionGreeks", b"optionGreeks", "tbq", b"tbq", "tsq", b"tsq", "vtt", b"vtt"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MarketFullFeed: _TypeAlias = MarketFullFeed  # noqa: Y015

@_typing.final
class IndexFullFeed(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LTPC_FIELD_NUMBER: _builtins.int
    MARKETOHLC_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ltpc(self) -> Global___LTPC: ...
    @_builtins.property
    def marketOHLC(self) -> Global___MarketOHLC: ...
    def __init__(
        self,
        *,
        ltpc: Global___LTPC | None = ...,
        marketOHLC: Global___MarketOHLC | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ltpc", b"ltpc", "marketOHLC", b"marketOHLC"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ltpc", b"ltpc", "marketOHLC", b"marketOHLC"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___IndexFullFeed: _TypeAlias = IndexFullFeed  # noqa: Y015

@_typing.final
class FullFeed(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MARKETFF_FIELD_NUMBER: _builtins.int
    INDEXFF_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def marketFF(self) -> Global___MarketFullFeed: ...
    @_builtins.property
    def indexFF(self) -> Global___IndexFullFeed: ...
    def __init__(
        self,
        *,
        marketFF: Global___MarketFullFeed | None = ...,
        indexFF: Global___IndexFullFeed | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["FullFeedUnion", b"FullFeedUnion", "indexFF", b"indexFF", "marketFF", b"marketFF"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["FullFeedUnion", b"FullFeedUnion", "indexFF", b"indexFF", "marketFF", b"marketFF"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_FullFeedUnion: _TypeAlias = _typing.Literal["marketFF", "indexFF"]  # noqa: Y015
    _WhichOneofArgType_FullFeedUnion: _TypeAlias = _typing.Literal["FullFeedUnion", b"FullFeedUnion"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_FullFeedUnion) -> _WhichOneofReturnType_FullFeedUnion | None: ...

Global___FullFeed: _TypeAlias = FullFeed  # noqa: Y015

@_typing.final
class FirstLevelWithGreeks(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LTPC_FIELD_NUMBER: _builtins.int
    FIRSTDEPTH_FIELD_NUMBER: _builtins.int
    OPTIONGREEKS_FIELD_NUMBER: _builtins.int
    VTT_FIELD_NUMBER: _builtins.int
    OI_FIELD_NUMBER: _builtins.int
    IV_FIELD_NUMBER: _builtins.int
    vtt: _builtins.int
    """volume traded today"""
    oi: _builtins.float
    """open interest"""
    iv: _builtins.float
    """implied volatility"""
    @_builtins.property
    def ltpc(self) -> Global___LTPC: ...
    @_builtins.property
    def firstDepth(self) -> Global___Quote: ...
    @_builtins.property
    def optionGreeks(self) -> Global___OptionGreeks: ...
    def __init__(
        self,
        *,
        ltpc: Global___LTPC | None = ...,
        firstDepth: Global___Quote | None = ...,
        optionGreeks: Global___OptionGreeks | None = ...,
        vtt: _builtins.int = ...,
        oi: _builtins.float = ...,
        iv: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["firstDepth", b"firstDepth", "ltpc", b"ltpc", "optionGreeks", b"optionGreeks"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["firstDepth", b"firstDepth", "iv", b"iv", "ltpc", b"ltpc", "oi", b"oi", "optionGreeks", b"optionGreeks", "vtt", b"vtt"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FirstLevelWithGreeks: _TypeAlias = FirstLevelWithGreeks  # noqa: Y015

@_typing.final
class Feed(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LTPC_FIELD_NUMBER: _builtins.int
    FULLFEED_FIELD_NUMBER: _builtins.int
    FIRSTLEVELWITHGREEKS_FIELD_NUMBER: _builtins.int
    REQUESTMODE_FIELD_NUMBER: _builtins.int
    requestMode: Global___RequestMode.ValueType
    @_builtins.property
    def ltpc(self) -> Global___LTPC: ...
    @_builtins.property
    def fullFeed(self) -> Global___FullFeed: ...
    @_builtins.property
    def firstLevelWithGreeks(self) -> Global___FirstLevelWithGreeks: ...
    def __init__(
        self,
        *,
        ltpc: Global___LTPC | None = ...,
        fullFeed: Global___FullFeed | None = ...,
        firstLevelWithGreeks: Global___FirstLevelWithGreeks | None = ...,
        requestMode: Global___RequestMode.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["FeedUnion", b"FeedUnion", "firstLevelWithGreeks", b"firstLevelWithGreeks", "fullFeed", b"fullFeed", "ltpc", b"ltpc"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["FeedUnion", b"FeedUnion", "firstLevelWithGreeks", b"firstLevelWithGreeks", "fullFeed", b"fullFeed", "ltpc", b"ltpc", "requestMode", b"requestMode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_FeedUnion: _TypeAlias = _typing.Literal["ltpc", "fullFeed", "firstLevelWithGreeks"]  # noqa: Y015
    _WhichOneofArgType_FeedUnion: _TypeAlias = _typing.Literal["FeedUnion", b"FeedUnion"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_FeedUnion) -> _WhichOneofReturnType_FeedUnion | None: ...

Global___Feed: _TypeAlias = Feed  # noqa: Y015

@_typing.final
class MarketInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class SegmentStatusEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: Global___MarketStatus.ValueType
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___MarketStatus.ValueType = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SEGMENTSTATUS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def segmentStatus(self) -> _containers.ScalarMap[_builtins.str, Global___MarketStatus.ValueType]: ...
    def __init__(
        self,
        *,
        segmentStatus: _abc.Mapping[_builtins.str, Global___MarketStatus.ValueType] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["segmentStatus", b"segmentStatus"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MarketInfo: _TypeAlias = MarketInfo  # noqa: Y015

@_typing.final
class FeedResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class FeedsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___Feed: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___Feed | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TYPE_FIELD_NUMBER: _builtins.int
    FEEDS_FIELD_NUMBER: _builtins.int
    CURRENTTS_FIELD_NUMBER: _builtins.int
    MARKETINFO_FIELD_NUMBER: _builtins.int
    type: Global___Type.ValueType
    currentTs: _builtins.int
    @_builtins.property
    def feeds(self) -> _containers.MessageMap[_builtins.str, Global___Feed]: ...
    @_builtins.property
    def marketInfo(self) -> Global___MarketInfo: ...
    def __init__(
        self,
        *,
        type: Global___Type.ValueType = ...,
        feeds: _abc.Mapping[_builtins.str, Global___Feed] | None = ...,
        currentTs: _builtins.int = ...,
        marketInfo: Global___MarketInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["marketInfo", b"marketInfo"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["currentTs", b"currentTs", "feeds", b"feeds", "marketInfo", b"marketInfo", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FeedResponse: _TypeAlias = FeedResponse  # noqa: Y015
